server:
  port: 8085

spring:
  application:
    name: springboot-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hello?useUnicode=true&characterEncoding=utf-8&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  table:
    auto: update
  database:
    type: mysql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config:
    classpath: logback.xml